// <auto-generated />
using System;
using FuCommunityWebDataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FuCommunityWebDataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241002023333_ver1")]
    partial class ver1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Document", b =>
                {
                    b.Property<int>("DocumentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DocumentID"));

                    b.Property<int?>("CourseID")
                        .HasColumnType("int");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("PostID")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("DocumentID");

                    b.HasIndex("CourseID");

                    b.HasIndex("PostID");

                    b.HasIndex("UserID");

                    b.ToTable("Document");

                    b.HasData(
                        new
                        {
                            DocumentID = 1,
                            CourseID = 1,
                            FileUrl = "aspnet_handbook.pdf",
                            Name = "ASP.NET Core Handbook",
                            UploadedAt = new DateTime(2024, 9, 22, 9, 33, 30, 989, DateTimeKind.Local).AddTicks(2463),
                            UserID = 1
                        },
                        new
                        {
                            DocumentID = 2,
                            FileUrl = "quantum_basics.pdf",
                            Name = "Quantum Basics PDF",
                            PostID = 2,
                            UploadedAt = new DateTime(2024, 9, 12, 9, 33, 30, 989, DateTimeKind.Local).AddTicks(2467),
                            UserID = 2
                        });
                });

            modelBuilder.Entity("FuCommunityWebModels.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryID");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            CategoryName = "Technology",
                            Description = "All about technology"
                        },
                        new
                        {
                            CategoryID = 2,
                            CategoryName = "Science",
                            Description = "Science topics"
                        },
                        new
                        {
                            CategoryID = 3,
                            CategoryName = "Art",
                            Description = "All about art"
                        });
                });

            modelBuilder.Entity("FuCommunityWebModels.Models.Comment", b =>
                {
                    b.Property<int>("CommentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommentID"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PostID")
                        .HasColumnType("int");

                    b.Property<int?>("QuestionID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("CommentID");

                    b.HasIndex("PostID");

                    b.HasIndex("QuestionID");

                    b.HasIndex("UserID");

                    b.ToTable("Comment");
                });

            modelBuilder.Entity("FuCommunityWebModels.Models.Course", b =>
                {
                    b.Property<int>("CourseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseID"));

                    b.Property<string>("CourseImage")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("CourseID");

                    b.HasIndex("UserID");

                    b.ToTable("Course");

                    b.HasData(
                        new
                        {
                            CourseID = 1,
                            CourseImage = "aspnet_core.png",
                            CreatedDate = new DateTime(2024, 9, 2, 9, 33, 30, 989, DateTimeKind.Local).AddTicks(2283),
                            Description = "An introductory course to ASP.NET Core.",
                            Price = 49.99m,
                            Status = "Active",
                            Title = "Learn ASP.NET Core",
                            UpdatedDate = new DateTime(2024, 10, 2, 9, 33, 30, 989, DateTimeKind.Local).AddTicks(2284),
                            UserID = 1
                        },
                        new
                        {
                            CourseID = 2,
                            CourseImage = "csharp_master.png",
                            CreatedDate = new DateTime(2024, 8, 13, 9, 33, 30, 989, DateTimeKind.Local).AddTicks(2288),
                            Description = "Advanced C# programming techniques.",
                            Price = 99.99m,
                            Status = "Active",
                            Title = "Master C# Programming",
                            UpdatedDate = new DateTime(2024, 9, 22, 9, 33, 30, 989, DateTimeKind.Local).AddTicks(2289),
                            UserID = 2
                        });
                });

            modelBuilder.Entity("FuCommunityWebModels.Models.Enrollment", b =>
                {
                    b.Property<int>("EnrollmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnrollmentID"));

                    b.Property<int>("CourseID")
                        .HasColumnType("int");

                    b.Property<int?>("DocumentID")
                        .HasColumnType("int");

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("EnrollmentID");

                    b.HasIndex("CourseID");

                    b.HasIndex("DocumentID");

                    b.HasIndex("UserID");

                    b.ToTable("Enrollment");

                    b.HasData(
                        new
                        {
                            EnrollmentID = 1,
                            CourseID = 2,
                            DocumentID = 1,
                            EnrollmentDate = new DateTime(2024, 9, 27, 9, 33, 30, 989, DateTimeKind.Local).AddTicks(2484),
                            Status = "Completed",
                            UserID = 1
                        },
                        new
                        {
                            EnrollmentID = 2,
                            CourseID = 1,
                            DocumentID = 2,
                            EnrollmentDate = new DateTime(2024, 9, 17, 9, 33, 30, 989, DateTimeKind.Local).AddTicks(2489),
                            Status = "InProgress",
                            UserID = 2
                        });
                });

            modelBuilder.Entity("FuCommunityWebModels.Models.IsVote", b =>
                {
                    b.Property<int>("IsVoteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IsVoteID"));

                    b.Property<int>("PostID")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("IsVoteID");

                    b.HasIndex("PostID");

                    b.HasIndex("UserID");

                    b.ToTable("IsVote");

                    b.HasData(
                        new
                        {
                            IsVoteID = 1,
                            PostID = 1,
                            UserID = 1
                        },
                        new
                        {
                            IsVoteID = 2,
                            PostID = 2,
                            UserID = 2
                        });
                });

            modelBuilder.Entity("FuCommunityWebModels.Models.Lesson", b =>
                {
                    b.Property<int>("LessonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LessonID"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CourseID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LessonUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("LessonID");

                    b.HasIndex("CourseID");

                    b.ToTable("Lesson");

                    b.HasData(
                        new
                        {
                            LessonID = 1,
                            Content = "In this lesson, you will learn the basics...",
                            CourseID = 1,
                            CreatedDate = new DateTime(2024, 9, 22, 9, 33, 30, 989, DateTimeKind.Local).AddTicks(2403),
                            LessonUrl = "intro_aspnet_core.mp4",
                            Status = "Completed",
                            Title = "Introduction to ASP.NET Core",
                            UpdatedDate = new DateTime(2024, 10, 2, 9, 33, 30, 989, DateTimeKind.Local).AddTicks(2403)
                        },
                        new
                        {
                            LessonID = 2,
                            Content = "This lesson covers advanced topics...",
                            CourseID = 2,
                            CreatedDate = new DateTime(2024, 8, 23, 9, 33, 30, 989, DateTimeKind.Local).AddTicks(2407),
                            LessonUrl = "advanced_csharp.mp4",
                            Status = "Completed",
                            Title = "C# Advanced Techniques",
                            UpdatedDate = new DateTime(2024, 9, 27, 9, 33, 30, 989, DateTimeKind.Local).AddTicks(2407)
                        });
                });

            modelBuilder.Entity("FuCommunityWebModels.Models.Post", b =>
                {
                    b.Property<int>("PostID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PostID"));

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PostImage")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("PostID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("UserID");

                    b.ToTable("Post");

                    b.HasData(
                        new
                        {
                            PostID = 1,
                            CategoryID = 1,
                            Content = "Blazor is a new web framework...",
                            CreatedDate = new DateTime(2024, 9, 17, 9, 33, 30, 989, DateTimeKind.Local).AddTicks(2314),
                            PostImage = "blazor_intro.png",
                            Status = "Published",
                            Title = "Introduction to Blazor",
                            UpdatedDate = new DateTime(2024, 10, 2, 9, 33, 30, 989, DateTimeKind.Local).AddTicks(2315),
                            UserID = 1
                        },
                        new
                        {
                            PostID = 2,
                            CategoryID = 2,
                            Content = "Quantum computing is an emerging field...",
                            CreatedDate = new DateTime(2024, 9, 7, 9, 33, 30, 989, DateTimeKind.Local).AddTicks(2318),
                            PostImage = "quantum_basics.png",
                            Status = "Published",
                            Title = "Quantum Computing Basics",
                            UpdatedDate = new DateTime(2024, 9, 27, 9, 33, 30, 989, DateTimeKind.Local).AddTicks(2319),
                            UserID = 2
                        });
                });

            modelBuilder.Entity("FuCommunityWebModels.Models.Question", b =>
                {
                    b.Property<int>("QuestionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestionID"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("QuestionID");

                    b.HasIndex("UserID");

                    b.ToTable("Question");

                    b.HasData(
                        new
                        {
                            QuestionID = 1,
                            Content = "Can someone explain dependency injection...",
                            CreatedDate = new DateTime(2024, 9, 12, 9, 33, 30, 989, DateTimeKind.Local).AddTicks(2342),
                            Status = "Open",
                            Title = "What is Dependency Injection?",
                            UpdatedDate = new DateTime(2024, 10, 2, 9, 33, 30, 989, DateTimeKind.Local).AddTicks(2343),
                            UserID = 1
                        },
                        new
                        {
                            QuestionID = 2,
                            Content = "Looking for an explanation on Docker basics...",
                            CreatedDate = new DateTime(2024, 9, 2, 9, 33, 30, 989, DateTimeKind.Local).AddTicks(2345),
                            Status = "Open",
                            Title = "What are the basics of Docker?",
                            UpdatedDate = new DateTime(2024, 9, 22, 9, 33, 30, 989, DateTimeKind.Local).AddTicks(2346),
                            UserID = 2
                        });
                });

            modelBuilder.Entity("FuCommunityWebModels.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserID");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            Active = true,
                            Email = "john@example.com",
                            LastLogin = new DateTime(2024, 10, 2, 9, 33, 30, 989, DateTimeKind.Local).AddTicks(2242),
                            Password = "hashedpassword123",
                            Points = 500,
                            RegistrationDate = new DateTime(2024, 10, 2, 9, 33, 30, 989, DateTimeKind.Local).AddTicks(2241),
                            Role = "Admin",
                            Username = "john_doe"
                        },
                        new
                        {
                            UserID = 2,
                            Active = true,
                            Email = "jane@example.com",
                            LastLogin = new DateTime(2024, 9, 30, 9, 33, 30, 989, DateTimeKind.Local).AddTicks(2257),
                            Password = "hashedpassword456",
                            Points = 300,
                            RegistrationDate = new DateTime(2024, 9, 22, 9, 33, 30, 989, DateTimeKind.Local).AddTicks(2248),
                            Role = "User",
                            Username = "jane_smith"
                        });
                });

            modelBuilder.Entity("FuCommunityWebModels.Models.UserInfo", b =>
                {
                    b.Property<int>("InfoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InfoID"));

                    b.Property<string>("AvatarImage")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("InfoID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("UserInfo");

                    b.HasData(
                        new
                        {
                            InfoID = 1,
                            AvatarImage = "john_avatar.png",
                            Bio = "Software Developer",
                            DOB = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "John Doe",
                            Gender = "M",
                            Phone = "123-456-7890",
                            UserID = 1
                        },
                        new
                        {
                            InfoID = 2,
                            AvatarImage = "jane_avatar.png",
                            Bio = "Data Scientist",
                            DOB = new DateTime(1992, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Jane Smith",
                            Gender = "F",
                            Phone = "987-654-3210",
                            UserID = 2
                        });
                });

            modelBuilder.Entity("Document", b =>
                {
                    b.HasOne("FuCommunityWebModels.Models.Course", "Course")
                        .WithMany("Documents")
                        .HasForeignKey("CourseID");

                    b.HasOne("FuCommunityWebModels.Models.Post", "Post")
                        .WithMany()
                        .HasForeignKey("PostID");

                    b.HasOne("FuCommunityWebModels.Models.User", "User")
                        .WithMany("Documents")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FuCommunityWebModels.Models.Comment", b =>
                {
                    b.HasOne("FuCommunityWebModels.Models.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostID");

                    b.HasOne("FuCommunityWebModels.Models.Question", "Question")
                        .WithMany("Comments")
                        .HasForeignKey("QuestionID");

                    b.HasOne("FuCommunityWebModels.Models.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("Question");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FuCommunityWebModels.Models.Course", b =>
                {
                    b.HasOne("FuCommunityWebModels.Models.User", "User")
                        .WithMany("Courses")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FuCommunityWebModels.Models.Enrollment", b =>
                {
                    b.HasOne("FuCommunityWebModels.Models.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Document", "Document")
                        .WithMany("Enrollments")
                        .HasForeignKey("DocumentID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FuCommunityWebModels.Models.User", "User")
                        .WithMany("Enrollments")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Document");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FuCommunityWebModels.Models.IsVote", b =>
                {
                    b.HasOne("FuCommunityWebModels.Models.Post", "Post")
                        .WithMany("Votes")
                        .HasForeignKey("PostID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FuCommunityWebModels.Models.User", "User")
                        .WithMany("Votes")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FuCommunityWebModels.Models.Lesson", b =>
                {
                    b.HasOne("FuCommunityWebModels.Models.Course", "Course")
                        .WithMany("Lessons")
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("FuCommunityWebModels.Models.Post", b =>
                {
                    b.HasOne("FuCommunityWebModels.Models.Category", "Category")
                        .WithMany("Posts")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FuCommunityWebModels.Models.User", "User")
                        .WithMany("Posts")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FuCommunityWebModels.Models.Question", b =>
                {
                    b.HasOne("FuCommunityWebModels.Models.User", "User")
                        .WithMany("Questions")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FuCommunityWebModels.Models.UserInfo", b =>
                {
                    b.HasOne("FuCommunityWebModels.Models.User", "User")
                        .WithOne("UserInfo")
                        .HasForeignKey("FuCommunityWebModels.Models.UserInfo", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Document", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("FuCommunityWebModels.Models.Category", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("FuCommunityWebModels.Models.Course", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Enrollments");

                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("FuCommunityWebModels.Models.Post", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Votes");
                });

            modelBuilder.Entity("FuCommunityWebModels.Models.Question", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("FuCommunityWebModels.Models.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Courses");

                    b.Navigation("Documents");

                    b.Navigation("Enrollments");

                    b.Navigation("Posts");

                    b.Navigation("Questions");

                    b.Navigation("UserInfo")
                        .IsRequired();

                    b.Navigation("Votes");
                });
#pragma warning restore 612, 618
        }
    }
}
